sonar.projectKey=d7dbbad3feaa9b16dc77e8c9f96451aac42f6ef4
sonar.organization=aliviee
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.exclusions=**/test/**